VIDEO_RESOLUTION:
  VIDEO_RES_X: 1080
  VIDEO_RES_Y: 1920

VIDEO_SETTINGS:
  OUTPUT_FOLDER: "output"
  OUTPUT_FILE: "video"
  OUTPUT_TYPE: "mp4"
  FPS: 25
  
VIDEO_TEST_SETTINGS:
  SAMPLE_RES_TEST_DURATION: 5